import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"; // Import CSS

import "./globals.css";
import ClientBootstrap from "./ClientBootstrap"; // Client component for JS logic
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "Car Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Epilogue:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header />
        <ClientBootstrap /> {/* Ensures Bootstrap JS is loaded */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
