import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";

export const metadata = {
  title: "NaylRental",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&family=Roboto+Slab&family=Roboto:wght@100;300;500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}
        <div id="videomodal"></div>
      </body>
    </html>
  );
}
